=== BEST-OF-RUN ===
              generation: 39
                   nodes: 11
                   depth: 6
                    hits: 847
TOP INDIVIDUAL:



-- #1 --
                    hits: 847
             raw fitness: 847.0000
    standardized fitness: 847.0000
        adjusted fitness: 0.9988
TREE:
 (log (/ extent
         (* (exp (/ (+ perimeter major) eccentricity)) extent)))
TREE-equ:
y = log((extent / (exp(((perimeter + major) / eccentricity)) * extent)))
