=== BEST-OF-RUN ===
              generation: 13
                   nodes: 9
                   depth: 5
                    hits: 903
TOP INDIVIDUAL:



-- #1 --
                    hits: 903
             raw fitness: 903.0000
    standardized fitness: 903.0000
        adjusted fitness: 0.9989
TREE:
 (log (exp (/ (* perimeter
                 (/ area -0.61055)) area)))
TREE-equ:
y = log(exp(((perimeter * (area / -0.61055)) / area)))
