=== BEST-OF-RUN ===
              generation: 33
                   nodes: 12
                   depth: 5
                    hits: 881
TOP INDIVIDUAL:



-- #1 --
                    hits: 881
             raw fitness: 881.0000
    standardized fitness: 881.0000
        adjusted fitness: 0.9989
TREE:
 (log (/ (exp (/ minor
                 (log eccentricity)))
         (- minor
            (/ extent area))))
TREE-equ:
y = log((exp((minor / log(eccentricity))) / (minor - (extent / area))))
