=== BEST-OF-RUN ===
              generation: 38
                   nodes: 10
                   depth: 5
                    hits: 901
TOP INDIVIDUAL:



-- #1 --
                    hits: 901
             raw fitness: 901.0000
    standardized fitness: 901.0000
        adjusted fitness: 0.9989
TREE:
 (log (exp (* (/ (* major eccentricity) -0.57094)
              (exp eccentricity))))
TREE-equ:
y = log(exp((((major * eccentricity) / -0.57094) * exp(eccentricity))))
