=== BEST-OF-RUN ===
              generation: 5
                   nodes: 9
                   depth: 4
                    hits: 873
TOP INDIVIDUAL:



-- #1 --
                    hits: 873
             raw fitness: 873.0000
    standardized fitness: 873.0000
        adjusted fitness: 0.9989
TREE:
 (/ -0.60673
    (* (exp perimeter)
       (exp (+ major minor))))
TREE-equ:
y = (-0.60673 / (exp(perimeter) * exp((major + minor))))
