=== BEST-OF-RUN ===
              generation: 34
                   nodes: 8
                   depth: 5
                    hits: 905
TOP INDIVIDUAL:



-- #1 --
                    hits: 905
             raw fitness: 905.0000
    standardized fitness: 905.0000
        adjusted fitness: 0.9989
TREE:
 (log (/ -0.04667
         (exp (* (log perimeter) -0.50063))))
TREE-equ:
y = log((-0.04667 / exp((log(perimeter) * -0.50063))))
